classDiagram
    class Estudiante {
        -id: int
        -nombre: string
        -email: string
        -carrera: string
        +registrar(): void
        +editarPerfil(): void
        +consultarCursosDisponibles(): List<Curso>
        +consultarCursosMatriculados(): List<Curso>
    }
 
    class Curso {
        -codigo: string
        -nombre: string
        -creditos: int
        +matricular(): void
        +retirar(): void
    }

    class Periodo {
        -ano: int
        -nombre: string
        -activo: boolean
        +iniciarPerido(): void
        +finalizarPeriodo(): void
    }

    class Grupo {
        -idCurso: string
        -idPeriodo: int
        -idProfesor: int
        -horario: string
        +asignarProfesor(): List<profesores>
        +definirHorario(): void
        +asignarGrupo(): void
    }

    class Profesor {
        -id: int
        -nombre: string
        -email: string
        +editarCurso(): void
        +pasarLista(): void
        +asignarTrabajo(): void
    }

    class Matricula {
        -idEstudiante: int
        -idMatricula: int
        -idGrupo: int
        -fechaMatricula: date
        +realizarMatricula(): void
        +cancelarMatricula(): void
    }

    Estudiante "1" --> "*" Matricula : matriculado en
    Matricula "*" --> "1" Grupo : pertenece a
    Grupo "*" --> "1" Curso : ofrece
    Grupo "1" --> "*" Profesor : enseña
    Grupo "1" --> "*" Periodo : en